name: ci-cd-front-spil

on:
  push:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Download flutter
        run: |
                wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_2.10.4-stable.tar.xz
                tar xf ~/Downloads/flutter_linux_2.10.4-stable.tar.xz
                ls -laR
